// ─────────────────────────────────────────────
// email.js — Send AI Investment Report via EmailJS
// Setup: https://www.emailjs.com
// 1. Create a free EmailJS account
// 2. Add an Email Service (Gmail, Outlook, etc.)
// 3. Create an Email Template with variables:
//    {{to_email}}, {{land_title}}, {{report_content}}
// 4. Replace YOUR_PUBLIC_KEY, YOUR_SERVICE_ID, YOUR_TEMPLATE_ID below
// ─────────────────────────────────────────────

// Initialize EmailJS with your public key
emailjs.init("YOUR_PUBLIC_KEY");

// Send investment report by email
async function sendReportByEmail(item, email) {
  if (!email || !email.includes("@")) {
    alert("Please enter a valid email address.");
    return;
  }

  const score = calcScore(item);

  const reportText = `
LANDINVEST — AI INVESTMENT REPORT
══════════════════════════════════

Property:     ${item.title}
Country:      ${item.country}
Price:        $${item.price.toLocaleString()}

INVESTMENT SCORE: ${score} / 100

── Score Breakdown ──
Location:       ${item.location} / 100
Growth:         ${item.growth} / 100
ROI:            ${item.roi} / 100
Risk:           ${item.risk} / 100
Liquidity:      ${item.liquidity} / 100
Infrastructure: ${item.infrastructure} / 100

── Investment Thesis ──
${item.thesis}

── Recommendation ──
${score >= 80 ? "STRONG BUY — High confidence investment opportunity." :
  score >= 65 ? "BUY — Solid fundamentals with acceptable risk." :
  score >= 50 ? "HOLD — Monitor closely before committing capital." :
               "CAUTION — Review risk factors before investing."}

──────────────────────────────────
Generated by LandInvest AI Platform
  `.trim();

  try {
    await emailjs.send("YOUR_SERVICE_ID", "YOUR_TEMPLATE_ID", {
      to_email: email,
      land_title: item.title,
      report_content: reportText,
      investment_score: score,
      property_price: "$" + item.price.toLocaleString(),
      property_country: item.country
    });
    alert("✓ Report sent to " + email);
  } catch (err) {
    console.error("EmailJS error:", err);
    alert("Failed to send report. Please try again or contact support.");
  }
}

// Investment score calculator (matches detail.html formula)
function calcScore(d) {
  return Math.round(
    d.location      * 0.25 +
    d.growth        * 0.20 +
    d.roi           * 0.20 +
    d.risk          * 0.15 +
    d.liquidity     * 0.10 +
    d.infrastructure * 0.10
  );
}
